In [1]:
from pathlib import Path
import sys

project_root = Path.cwd().parent
sys.path.append(str(project_root))

In [2]:
import pandas as pandas
import numpy as np

from src.data_loader import DataLoader

In [3]:
loader = DataLoader('../data/raw/kc_house_data.csv')
df = loader.load_data()

In [4]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [6]:
loader.dataset_info()

{'Rows': 21613, 'Columns': 21, 'Memory (MB)': np.float64(3.77)}

In [7]:
loader.missing_summary()

               Missing Count  Missing Percentage
id                         0                 0.0
date                       0                 0.0
price                      0                 0.0
bedrooms                   0                 0.0
bathrooms                  0                 0.0
sqft_living                0                 0.0
sqft_lot                   0                 0.0
floors                     0                 0.0
waterfront                 0                 0.0
view                       0                 0.0
condition                  0                 0.0
grade                      0                 0.0
sqft_above                 0                 0.0
sqft_basement              0                 0.0
yr_built                   0                 0.0
yr_renovated               0                 0.0
zipcode                    0                 0.0
lat                        0                 0.0
long                       0                 0.0
sqft_living15              0                 0.0
sqft_lot15                 0                 0.0

In [8]:
loader.duplicate_summary()

{'Duplicate Rows': np.int64(0), 'Duplicate Percentage': np.float64(0.0)}

In [9]:
loader.statistical_summary()

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
id,21613.0,NaN,NaN,NaN,4580301520.864988,2876565571.312057,1000102.0,2123049194.0,3904930410.0,7308900445.0,9900000190.0
date,21613,372,20140623T000000,142,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price,21613.0,NaN,NaN,NaN,540088.141767,367127.196483,75000.0,321950.0,450000.0,645000.0,7700000.0
bedrooms,21613.0,NaN,NaN,NaN,3.370842,0.930062,0.0,3.0,3.0,4.0,33.0
bathrooms,21613.0,NaN,NaN,NaN,2.114757,0.770163,0.0,1.75,2.25,2.5,8.0
sqft_living,21613.0,NaN,NaN,NaN,2079.899736,918.440897,290.0,1427.0,1910.0,2550.0,13540.0
sqft_lot,21613.0,NaN,NaN,NaN,15106.967566,41420.511515,520.0,5040.0,7618.0,10688.0,1651359.0
floors,21613.0,NaN,NaN,NaN,1.494309,0.539989,1.0,1.0,1.5,2.0,3.5
waterfront,21613.0,NaN,NaN,NaN,0.007542,0.086517,0.0,0.0,0.0,0.0,1.0
view,21613.0,NaN,NaN,NaN,0.234303,0.766318,0.0,0.0,0.0,0.0,4.0
condition,21613.0,NaN,NaN,NaN,3.40943,0.650743,1.0,3.0,3.0,4.0,5.0
grade,21613.0,NaN,NaN,NaN,7.656873,1.175459,1.0,7.0,7.0,8.0,13.0
sqft_above,21613.0,NaN,NaN,NaN,1788.390691,828.090978,290.0,1190.0,1560.0,2210.0,9410.0
sqft_basement,21613.0,NaN,NaN,NaN,291.509045,442.575043,0.0,0.0,0.0,560.0,4820.0
yr_built,21613.0,NaN,NaN,NaN,1971.005136,29.373411,1900.0,1951.0,1975.0,1997.0,2015.0
yr_renovated,21613.0,NaN,NaN,NaN,84.402258,401.67924,0.0,0.0,0.0,0.0,2015.0
zipcode,21613.0,NaN,NaN,NaN,98077.939805,53.505026,98001.0,98033.0,98065.0,98118.0,98199.0
lat,21613.0,NaN,NaN,NaN,47.560053,0.138564,47.1559,47.471,47.5718,47.678,47.7776
long,21613.0,NaN,NaN,NaN,-122.213896,0.140828,-122.519,-122.328,-122.23,-122.125,-121.315
sqft_living15,21613.0,NaN,NaN,NaN,1986.552492,685.391304,399.0,1490.0,1840.0,2360.0,6210.0
sqft_lot15,21613.0,NaN,NaN,NaN,12768.455652,27304.179631,651.0,5100.0,7620.0,10083.0,871200.0