In [1]:
from pathlib import Path
import sys

project_root = Path.cwd().parent
sys.path.append(str(project_root))

In [2]:
import pandas as pandas
import numpy as np

from src.data_loader import DataLoader

In [3]:
loader = DataLoader('../data/raw/kc_house_data.csv')
df = loader.load_data()

In [4]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [5]:
loader.dataset_info()

{'Rows': 21613,
 'Columns': 21,
 'Features': ['id',
  'date',
  'price',
  'bedrooms',
  'bathrooms',
  'sqft_living',
  'sqft_lot',
  'floors',
  'waterfront',
  'view',
  'condition',
  'grade',
  'sqft_above',
  'sqft_basement',
  'yr_built',
  'yr_renovated',
  'zipcode',
  'lat',
  'long',
  'sqft_living15',
  'sqft_lot15'],
 'Memory (MB)': np.float64(3.77),
 'Duplicate Columns': np.int64(0)}

In [6]:
loader.missing_summary()

               Missing Count  Missing Percentage
id                         0                 0.0
date                       0                 0.0
price                      0                 0.0
bedrooms                   0                 0.0
bathrooms                  0                 0.0
sqft_living                0                 0.0
sqft_lot                   0                 0.0
floors                     0                 0.0
waterfront                 0                 0.0
view                       0                 0.0
condition                  0                 0.0
grade                      0                 0.0
sqft_above                 0                 0.0
sqft_basement              0                 0.0
yr_built                   0                 0.0
yr_renovated               0                 0.0
zipcode                    0                 0.0
lat                        0                 0.0
long                       0                 0.0
sqft_living15              0                 0.0
sqft_lot15                 0                 0.0

In [7]:
loader.duplicate_summary()

{'Duplicate Rows': np.int64(0), 'Duplicate Percentage': np.float64(0.0)}

In [8]:
loader.statistical_summary()

,count,mean,std,min,25%,50%,75%,max
id,21613.0,4.580302e+09,2.876566e+09,1.000102e+06,2.123049e+09,3.904930e+09,7.308900e+09,9.900000e+09
price,21613.0,5.400881e+05,3.671272e+05,7.500000e+04,3.219500e+05,4.500000e+05,6.450000e+05,7.700000e+06
bedrooms,21613.0,3.370842e+00,9.300618e-01,0.000000e+00,3.000000e+00,3.000000e+00,4.000000e+00,3.300000e+01
bathrooms,21613.0,2.114757e+00,7.701632e-01,0.000000e+00,1.750000e+00,2.250000e+00,2.500000e+00,8.000000e+00
sqft_living,21613.0,2.079900e+03,9.184409e+02,2.900000e+02,1.427000e+03,1.910000e+03,2.550000e+03,1.354000e+04
sqft_lot,21613.0,1.510697e+04,4.142051e+04,5.200000e+02,5.040000e+03,7.618000e+03,1.068800e+04,1.651359e+06
floors,21613.0,1.494309e+00,5.399889e-01,1.000000e+00,1.000000e+00,1.500000e+00,2.000000e+00,3.500000e+00
waterfront,21613.0,7.541757e-03,8.651720e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
view,21613.0,2.343034e-01,7.663176e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
condition,21613.0,3.409430e+00,6.507430e-01,1.000000e+00,3.000000e+00,3.000000e+00,4.000000e+00,5.000000e+00
grade,21613.0,7.656873e+00,1.175459e+00,1.000000e+00,7.000000e+00,7.000000e+00,8.000000e+00,1.300000e+01
sqft_above,21613.0,1.788391e+03,8.280910e+02,2.900000e+02,1.190000e+03,1.560000e+03,2.210000e+03,9.410000e+03
sqft_basement,21613.0,2.915090e+02,4.425750e+02,0.000000e+00,0.000000e+00,0.000000e+00,5.600000e+02,4.820000e+03
yr_built,21613.0,1.971005e+03,2.937341e+01,1.900000e+03,1.951000e+03,1.975000e+03,1.997000e+03,2.015000e+03
yr_renovated,21613.0,8.440226e+01,4.016792e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.015000e+03
zipcode,21613.0,9.807794e+04,5.350503e+01,9.800100e+04,9.803300e+04,9.806500e+04,9.811800e+04,9.819900e+04
lat,21613.0,4.756005e+01,1.385637e-01,4.715590e+01,4.747100e+01,4.757180e+01,4.767800e+01,4.777760e+01
long,21613.0,-1.222139e+02,1.408283e-01,-1.225190e+02,-1.223280e+02,-1.222300e+02,-1.221250e+02,-1.213150e+02
sqft_living15,21613.0,1.986552e+03,6.853913e+02,3.990000e+02,1.490000e+03,1.840000e+03,2.360000e+03,6.210000e+03
sqft_lot15,21613.0,1.276846e+04,2.730418e+04,6.510000e+02,5.100000e+03,7.620000e+03,1.008300e+04,8.712000e+05

In [9]:
loader.feature_summary()

              Data Type  Unique Values  Missing Count  Missing Percentage
id                int64          21436              0                 0.0
date                str            372              0                 0.0
price           float64           4028              0                 0.0
bedrooms          int64             13              0                 0.0
bathrooms       float64             30              0                 0.0
sqft_living       int64           1038              0                 0.0
sqft_lot          int64           9782              0                 0.0
floors          float64              6              0                 0.0
waterfront        int64              2              0                 0.0
view              int64              5              0                 0.0
condition         int64              5              0                 0.0
grade             int64             12              0                 0.0
sqft_above        int64            946              0                 0.0
sqft_basement     int64            306              0                 0.0
yr_built          int64            116              0                 0.0
yr_renovated      int64             70              0                 0.0
zipcode           int64             70              0                 0.0
lat             float64           5034              0                 0.0
long            float64            752              0                 0.0
sqft_living15     int64            777              0                 0.0
sqft_lot15        int64           8689              0                 0.0

In [10]:
loader.data_types